### ISSUE TITLE
`verifyAndReceive()` functionality deprecated - @octokit/webhooks

### ISSUE THREAD

**Issue by BigSamu** [BigSamu/OpenSearch-bot#16]
When using the `@octokit/webhooks` package and running the express server the following warning is received:

```
[@octokit/webhooks] Passing a JSON payload object to `verifyAndReceive()` is deprecated and the functionality will be removed in a future release of `@octokit/webhooks`
```

It is required to find a fix to this issue, so the tool don't break in the future

**Comment by ashwin-pc** [comment]
Whats the alternative here?

**Comment by BigSamu** [comment]
Hi @ashwin-pc, I already solved this issue yesterday. It was required to use the latest version of @octokit/webhooks. Closing this issue
