### ISSUE TITLE
Refactor `deleteFileByPath()` and createOrUpdateFileByPath() function to check for the existence of a file before attempting to delete

### ISSUE THREAD

**Issue by JohnathonBowers** [BigSamu/OpenSearch-bot#42]

**Comment by BigSamu** [comment]
The complete context of this is in this [thread](https://github.com/BigSamu/OpenSearch-bot/pull/41#discussion_r1438895007). Pull request #41 was approved to not postpone the merging of new features in code.

Still, it is suggested that the code review in PR be solved in this issue.

**Comment by BigSamu** [comment]
@JohnathonBowers,

I just opened PR #48. I would appreciate your review before merging.
