### ISSUE TITLE
Revise README to be more concise

### ISSUE THREAD

**Issue by JohnathonBowers** [BigSamu/OpenSearch-bot#7]

**Comment by BigSamu** [comment]
@JohnathonBowers, 

Can you add a Readme for this Github App. Now, the usage of this is much more significant. It is not only for creating changesets. His functionality could be expanded to many tasks, such as for example handle the release notes process. I would think adding the readme we already have as functionalities of the bot and introduce this tool as a bot for automation for OpenSearch project.

What do you think?

**Comment by JohnathonBowers** [comment]
Closing this issue as it was resolved by PR #33 .
